/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public static int Tri(int n) {
		int res = 0;
		for (int i = n; i > 0; i--) {
			res += i;
		}
		return res;
	}
	public static int Lazy(int n) {
		return (n*n + n +2)/2;
	}
	public static void main(String[] args) {
		try{

			if(Integer.parseInt(args[1]) < 0){
				System.out.println("non-negative integer should be used");
				System.exit(1);
			}
			
			if(args[0].equals("triangle")){
				System.out.println(App.Tri(Integer.parseInt(args[1])));
			} else if(args[0].equals("lazy")) {
				System.out.println(App.Lazy(Integer.parseInt(args[1])));
			} else {
				System.out.println("Invalid arg");
				System.exit(1);
			}
		} catch(Exception e){

			System.out.println("There should be 2 args");
			System.exit(1);

		}
	}
}
