/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

	public static int Tri(int n) {
		return (n*(n+1))/2;
	}

	public static int Lazy(int n) {
		return (n*n + n +2)/2;
	}

	public static void main(String[] args) {
		try{

			if(args[0].equals("triangle")){
				System.out.println("Tri(" + args[1] + ") = " + App.Tri(Integer.parseInt(args[1])));
			} else if(args[0].equals("lazy")) {
				System.out.println("Lazy(" + args[1] + ") = " + App.Lazy(Integer.parseInt(args[1])));
			} else {
				System.out.println("First argument should be \"triangle\" or \"lazy\"");
				System.exit(1);
			}

			if(Integer.parseInt(args[1]) < 0){
				System.out.println("Second argument should be a non-negative integer");
				System.exit(2);
			}

		} catch(Exception e){

			System.out.println("Arguments not formatted properly");
			System.exit(3);

		}
	}
}
