/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static int Tri(int n) {
    	int res = 0;
    		for(int i = n;i > 0; i--){
    			res += i;
    		}
        return res;
    }

    public static void main(String[] args) {
        System.out.println(App.Tri(5) + "\nShould be 15");
    }
}
