/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasTri() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.Tri(5));
        assertEquals(15,classUnderTest.Tri(5));
    }
}
